name: Submit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    if: |
      github.event_name == 'pull_request' && github.event.pull_request.merged == true ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: ryohidaka/wxt-submit@v1.0.0
        with:
          # For Chrome Extension
          chrome: false
          chrome-extension-id: ""
          chrome-client-id: ${{ secrets.CHROME_CLIENT_ID }}
          chrome-client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          chrome-refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

          # For Firefox Addon
          firefox: false
          firefox-extension-id: ""
          firefox-jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          firefox-jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}

          # For Edge Extension
          edge: false
          edge-product-id: ""
          edge-client-id: ${{ secrets.EDGE_CLIENT_ID }}
          edge-client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          edge-access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
